stages:
  data_ingestion:
    cmd: python src/ChestClassifier/pipeline/step_1_data_ingestion.py
    deps:
      - src/ChestClassifier/pipeline/step_1_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chest-CT-Scan-data

  prepare_base_model:
    cmd: python src/ChestClassifier/pipeline/step_2_prepare_base_model.py
    deps:
      - src/ChestClassifier/pipeline/step_2_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/ChestClassifier/pipeline/step_3_training.py
    deps:
      - src/ChestClassifier/pipeline/step_3_training.py
      - config/config.yaml
      - artifacts/prepare_base_model
      - artifacts/data_ingestion/Chest-CT-Scan-data
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/trained_model.h5

  evaluation:
    cmd: python src/ChestClassifier/pipeline/step_4_evaluation.py
    deps:
      - src/ChestClassifier/pipeline/step_4_evaluation.py
      - config/config.yaml
      - artifacts/training/trained_model.h5
      - artifacts/data_ingestion/Chest-CT-Scan-data
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: false



